{
  "openapi": "3.0.0",
  "info": {
    "title": "Hackyeah jak doczlapie",
    "version": "1.0.0",
    "description": ""
  },
  "components": {
    "responses": {
      "Forbidden": {
        "description": "Access token is missing or invalid"
      },
      "Accepted": {
        "description": "The request was accepted"
      },
      "Created": {
        "description": "The resource has been created"
      },
      "NotFound": {
        "description": "The resource has been created"
      },
      "NotAcceptable": {
        "description": "The resource has been created"
      }
    },
    "securitySchemes": {
      "BearerAuth": {
        "type": "http",
        "scheme": "bearer"
      },
      "BasicAuth": {
        "type": "http",
        "scheme": "basic"
      },
      "ApiKeyAuth": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-Key"
      }
    },
    "schemas": {
      "Any": {
        "description": "Any JSON object not defined as schema"
      },
      "PaginationMeta": {
        "type": "object",
        "properties": {
          "total": {
            "type": "number",
            "example": 100,
            "nullable": false
          },
          "page": {
            "type": "number",
            "example": 2,
            "nullable": false
          },
          "perPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "currentPage": {
            "type": "number",
            "example": 3,
            "nullable": false
          },
          "lastPage": {
            "type": "number",
            "example": 10,
            "nullable": false
          },
          "firstPage": {
            "type": "number",
            "example": 1,
            "nullable": false
          },
          "lastPageUrl": {
            "type": "string",
            "example": "/?page=10",
            "nullable": false
          },
          "firstPageUrl": {
            "type": "string",
            "example": "/?page=1",
            "nullable": false
          },
          "nextPageUrl": {
            "type": "string",
            "example": "/?page=6",
            "nullable": false
          },
          "previousPageUrl": {
            "type": "string",
            "example": "/?page=5",
            "nullable": false
          }
        }
      },
      "Condition": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 298
          },
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "description": {
            "type": "string",
            "example": "Lorem ipsum dolor sit amet"
          },
          "created_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          }
        },
        "description": "Condition (Model)"
      },
      "Route": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 504
          },
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "operator": {
            "type": "string",
            "example": "Lorem Ipsum"
          },
          "type": {
            "$ref": "#/components/schemas/\"bus\"",
            "example": null
          },
          "stops": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Stop",
              "example": null
            }
          },
          "route_stops": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/RouteStop",
              "example": null
            }
          },
          "schedules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Schedule",
              "example": null
            }
          },
          "created_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          }
        },
        "description": "Route (Model)"
      },
      "RouteStop": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 254
          },
          "route_id": {
            "type": "number",
            "example": 791
          },
          "stop_id": {
            "type": "number",
            "example": 65
          },
          "route": {
            "$ref": "#/components/schemas/Route",
            "example": null
          },
          "stop": {
            "$ref": "#/components/schemas/Stop",
            "example": null
          },
          "schedules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Schedule",
              "example": null
            }
          }
        },
        "description": "RouteStop (Model)"
      },
      "Schedule": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 999
          },
          "time": {
            "type": "string",
            "example": "Lorem Ipsum"
          },
          "sequence": {
            "type": "number",
            "example": 233
          },
          "destination": {
            "type": "string",
            "example": "Lorem Ipsum"
          },
          "conditions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Condition",
              "example": null
            }
          },
          "route_stop_id": {
            "type": "number",
            "example": 831
          },
          "run": {
            "type": "number",
            "example": 640
          },
          "route_stop": {
            "$ref": "#/components/schemas/RouteStop",
            "example": null
          },
          "created_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          }
        },
        "description": "Schedule (Model)"
      },
      "Stop": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 675
          },
          "name": {
            "type": "string",
            "example": "John Doe"
          },
          "schedules": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Schedule",
              "example": null
            }
          },
          "location": {
            "$ref": "#/components/schemas/GeoJSONPoint",
            "example": null
          },
          "type": {
            "$ref": "#/components/schemas/\"bus\"",
            "example": null
          },
          "routes": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Route",
              "example": null
            }
          },
          "created_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          },
          "updated_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          }
        },
        "description": "Stop (Model)"
      },
      "Track": {
        "type": "object",
        "required": [],
        "properties": {
          "id": {
            "type": "number",
            "example": 665
          },
          "created_at": {
            "type": "string",
            "example": "2021-03-23T16:13:08.489+01:00",
            "format": "date-time"
          },
          "route_id": {
            "type": "number",
            "example": 35
          },
          "run": {
            "type": "number",
            "example": 645
          },
          "location": {
            "$ref": "#/components/schemas/GeoJSONPoint",
            "example": null
          },
          "route": {
            "$ref": "#/components/schemas/Route",
            "example": null
          }
        },
        "description": "Track (Model)"
      },
      "findRouteValidator": {
        "type": "object",
        "properties": {
          "fromLatitude": {
            "type": "number",
            "example": -90,
            "minimum": -90,
            "maximum": 90,
            "required": true
          },
          "fromLongitude": {
            "type": "number",
            "example": -180,
            "minimum": -180,
            "maximum": 180,
            "required": true
          },
          "toLatitude": {
            "type": "number",
            "example": -90,
            "minimum": -90,
            "maximum": 90,
            "required": true
          },
          "toLongitude": {
            "type": "number",
            "example": -180,
            "minimum": -180,
            "maximum": 180,
            "required": true
          },
          "radius": {
            "type": "number",
            "example": 18
          }
        },
        "example": {
          "fromLatitude": -90,
          "fromLongitude": -180,
          "toLatitude": -90,
          "toLongitude": -180,
          "radius": 18
        },
        "description": "findRouteValidator (Validator)"
      },
      "nearbyRouteValidator": {
        "type": "object",
        "properties": {
          "latitude": {
            "type": "number",
            "example": -90,
            "minimum": -90,
            "maximum": 90,
            "required": true
          },
          "longitude": {
            "type": "number",
            "example": -180,
            "minimum": -180,
            "maximum": 180,
            "required": true
          },
          "radius": {
            "type": "number",
            "example": 38
          }
        },
        "example": {
          "latitude": -90,
          "longitude": -180,
          "radius": 38
        },
        "description": "nearbyRouteValidator (Validator)"
      },
      "storeTrackingValidator": {
        "type": "object",
        "properties": {
          "coordinates": {
            "type": "object",
            "properties": {
              "latitude": {
                "type": "number",
                "example": -90,
                "minimum": -90,
                "maximum": 90,
                "required": true
              },
              "longitude": {
                "type": "number",
                "example": -180,
                "minimum": -180,
                "maximum": 180,
                "required": true
              }
            },
            "required": true
          },
          "run": {
            "type": "number",
            "example": 1,
            "minimum": 1,
            "required": true
          }
        },
        "example": {
          "coordinates": {
            "latitude": -90,
            "longitude": -180
          },
          "run": 1
        },
        "description": "storeTrackingValidator (Validator)"
      }
    }
  },
  "paths": {
    "/api/v1/routes": {
      "get": {
        "summary": "Routes - Get routes based on start and end locations (index)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/routes_controller.ts_ - **index**",
        "parameters": [
          {
            "in": "query",
            "name": " fromLatitude",
            "description": "(Optional) Filter schedules by starting latitude",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": " fromLongitude",
            "description": "(Optional) Filter schedules by starting longitude",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": " toLatitude",
            "description": "(Optional) Filter schedules by destination latitude",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": " toLongitude",
            "description": "(Optional) Filter schedules by destination longitude",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": "radius",
            "description": "(Optional) in meters, default is 1000",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          }
        ],
        "tags": ["ROUTES"],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object"
                  }
                },
                "example": [
                  {
                    "departure": {
                      "name": "KRAPKOWICE | Kaufland",
                      "id": 21,
                      "coordinates": {
                        "longitude": 17.986,
                        "latitude": 50.489
                      },
                      "time": "17:58:00",
                      "distance": 978
                    },
                    "arrival": {
                      "name": "OPOLE GŁÓWNE",
                      "id": 49,
                      "coordinates": {
                        "longitude": 17.925,
                        "latitude": 50.662
                      },
                      "time": "18:47:00",
                      "distance": 0
                    },
                    "travel_time": 49,
                    "transfers": 2,
                    "routes": [
                      {
                        "id": 2,
                        "name": "LUZ Krapkowice  Strzelce Opolskie",
                        "operator": "LUZ",
                        "type": "bus",
                        "run": 52,
                        "departure": {
                          "name": "KRAPKOWICE | Kaufland",
                          "id": 21,
                          "coordinates": {
                            "longitude": 17.986,
                            "latitude": 50.489
                          },
                          "time": "18:10:00"
                        },
                        "arrival": {
                          "name": "KRAPKOWICE | Osiedle 1000lecia",
                          "id": 18,
                          "coordinates": {
                            "longitude": 17.973,
                            "latitude": 50.478
                          },
                          "time": "18:14:00"
                        },
                        "travel_time": 4,
                        "destination": "KRAPKOWICE"
                      },
                      {
                        "id": 2,
                        "name": "LUZ Krapkowice  Strzelce Opolskie",
                        "operator": "LUZ",
                        "type": "bus",
                        "run": 42,
                        "departure": {
                          "name": "KRAPKOWICE | Osiedle 1000lecia",
                          "id": 18,
                          "coordinates": {
                            "longitude": 17.973,
                            "latitude": 50.478
                          },
                          "time": "18:21:00"
                        },
                        "arrival": {
                          "name": "GOGOLIN | Dworzec Kolejowy",
                          "id": 24,
                          "coordinates": {
                            "longitude": 18.024,
                            "latitude": 50.491
                          },
                          "time": "18:31:00"
                        },
                        "travel_time": 10,
                        "destination": "STRZELCE OPOLSKIE"
                      },
                      {
                        "id": 3,
                        "name": "POLREGIO KędzierzynKoźle  Opole Główne",
                        "operator": "POLREGIO",
                        "type": "train",
                        "run": 68,
                        "departure": {
                          "name": "GOGOLIN",
                          "id": 44,
                          "coordinates": {
                            "longitude": 18.025,
                            "latitude": 50.49
                          },
                          "time": "18:35:00"
                        },
                        "arrival": {
                          "name": "OPOLE GŁÓWNE",
                          "id": 49,
                          "coordinates": {
                            "longitude": 17.925,
                            "latitude": 50.662
                          },
                          "time": "18:47:00"
                        },
                        "travel_time": 12,
                        "destination": "OPOLE GŁÓWNE"
                      }
                    ]
                  }
                ]
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          }
        },
        "security": []
      }
    },
    "/api/v1/routes/{id}": {
      "get": {
        "summary": "Routes - Get route details (show)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/routes_controller.ts_ - **show**",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "The ID of the route to retrieve @example(1)",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": "destination",
            "description": "(Optional) Filter schedules by destination",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          }
        ],
        "tags": ["ROUTES"],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": 2,
                    "name": "LUZ Krapkowice Strzelce Opolskie",
                    "type": "bus",
                    "operator": "LUZ",
                    "destinations": {
                      "type": "object",
                      "properties": {
                        "0": "KRAPKOWICE",
                        "1": "STRZELCE OPOLSKIE"
                      }
                    },
                    "stops": {
                      "type": "object",
                      "properties": {
                        "0": {
                          "type": "object",
                          "properties": {
                            "id": 17,
                            "name": "KRAPKOWICE ul. Prudnicka",
                            "type": "bus",
                            "coordinates": {
                              "type": "object",
                              "properties": {
                                "longitude": 17.965,
                                "latitude": 50.471
                              }
                            },
                            "schedules": {
                              "type": "object",
                              "properties": {
                                "0": {
                                  "type": "object",
                                  "properties": {
                                    "id": 663,
                                    "time": "06:30:00",
                                    "destination": "KRAPKOWICE",
                                    "run": 1,
                                    "conditions": {
                                      "type": "object",
                                      "properties": {
                                        "0": {
                                          "type": "object",
                                          "properties": {
                                            "id": 1,
                                            "name": "D",
                                            "description": "Kursuje od poniedziałku do piątku oprócz świąt"
                                          }
                                        }
                                      }
                                    }
                                  }
                                },
                                "1": {
                                  "type": "object",
                                  "properties": {
                                    "id": 423,
                                    "time": "06:50:00",
                                    "destination": "STRZELCE OPOLSKIE",
                                    "run": 1,
                                    "conditions": {
                                      "type": "object",
                                      "properties": {
                                        "0": {
                                          "type": "object",
                                          "properties": {
                                            "id": 1,
                                            "name": "D",
                                            "description": "Kursuje od poniedziałku do piątku oprócz świąt"
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "example": {
                  "id": 2,
                  "name": "LUZ Krapkowice Strzelce Opolskie",
                  "type": "bus",
                  "operator": "LUZ",
                  "destinations": ["KRAPKOWICE", "STRZELCE OPOLSKIE"],
                  "stops": [
                    {
                      "id": 17,
                      "name": "KRAPKOWICE ul. Prudnicka",
                      "type": "bus",
                      "coordinates": {
                        "longitude": 17.965,
                        "latitude": 50.471
                      },
                      "schedules": [
                        {
                          "id": 663,
                          "time": "06:30:00",
                          "destination": "KRAPKOWICE",
                          "run": 1,
                          "conditions": [
                            {
                              "id": 1,
                              "name": "D",
                              "description": "Kursuje od poniedziałku do piątku oprócz świąt"
                            }
                          ]
                        },
                        {
                          "id": 423,
                          "time": "06:50:00",
                          "destination": "STRZELCE OPOLSKIE",
                          "run": 1,
                          "conditions": [
                            {
                              "id": 1,
                              "name": "D",
                              "description": "Kursuje od poniedziałku do piątku oprócz świąt"
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          }
        },
        "security": []
      }
    },
    "/api/v1/stops": {
      "get": {
        "summary": "Stops - Get all nearby stops (index)",
        "description": "Returns **200** (OK) as **application/json**\n\n _app/controllers/stops_controller.ts_ - **index**",
        "parameters": [
          {
            "in": "query",
            "name": "longitude",
            "description": "",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": "latitude",
            "description": "",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          },
          {
            "in": "query",
            "name": "radius",
            "description": "(Optional) in meters",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          }
        ],
        "tags": ["STOPS"],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": 17,
                    "type": "bus",
                    "name": "KRAPKOWICE | ul. Prudnicka",
                    "routes": {
                      "type": "object",
                      "properties": {
                        "0": {
                          "type": "object",
                          "properties": {
                            "id": 2,
                            "name": "LUZ Krapkowice Strzelce Opolskie",
                            "operator": "LUZ"
                          }
                        }
                      }
                    },
                    "coordinates": {
                      "type": "object",
                      "properties": {
                        "longitude": 17.965,
                        "latitude": 50.471
                      }
                    },
                    "distance": 355
                  }
                },
                "example": {
                  "id": 17,
                  "type": "bus",
                  "name": "KRAPKOWICE | ul. Prudnicka",
                  "routes": [
                    {
                      "id": 2,
                      "name": "LUZ Krapkowice Strzelce Opolskie",
                      "operator": "LUZ"
                    }
                  ],
                  "coordinates": {
                    "longitude": 17.965,
                    "latitude": 50.471
                  },
                  "distance": 355
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          }
        },
        "security": []
      }
    },
    "/api/v1/stops/{id}": {
      "get": {
        "summary": "Stops - Get stop details (show)",
        "description": "Returns **200** (OK) as **text/plain**\n\n _app/controllers/stops_controller.ts_ - **show**",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "The ID of the stop to retrieve @example(1)",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          }
        ],
        "tags": ["STOPS"],
        "responses": {
          "200": {
            "content": {
              "text/plain": {
                "example": "{\"id\": 17,\"name\":\"KRAPKOWICE | ul. Prudnicka\", \"type\":\"bus\",\"coordinates\": {\"longitude\": 17.965,\"latitude\": 50.471  },\"routes\": [{\"name\": \"LUZ Krapkowice Strzelce Opolskie\", \"type\":\"bus\",\"id\": 2,\"operator\": \"LUZ\",\"destinations\": [\"KRAPKOWICE\",\"STRZELCE OPOLSKIE\"],\"schedules\": [{\"id\": 663,\"time\": \"06:30:00\",\"destination\": \"KRAPKOWICE\",\"run\": 1,\"conditions\": [{\"name\": \"D\",\"description\": \"Kursuje od poniedziałku do piątku oprócz świąt\",\"id\": 1}]}},{\"id\": 423,\"time\": \"06:50:00\",\"destination\": \"STRZELCE OPOLSKIE\",\"run\": 1,\"conditions\": [{\"name\": \"D\",\"description\": \"Kursuje od poniedziałku do piątku oprócz świąt\",\"id\": 1}]}]}]}"
              }
            },
            "description": "Returns **200** (OK) as **text/plain**"
          }
        },
        "security": []
      }
    },
    "/api/v1/routes/{id}/tracks": {
      "post": {
        "summary": "Trackings - Store user tracking data (store)",
        "description": "\n\n _app/controllers/tracks_controller.ts_ - **store**",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "description": "The ID of the route to track @example(1)",
            "schema": {
              "example": null,
              "type": "string"
            },
            "required": false
          }
        ],
        "tags": ["TRACKS"],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Track"
                },
                "example": {
                  "id": 665,
                  "created_at": "2021-03-23T16:13:08.489+01:00",
                  "route_id": 35,
                  "run": 645
                }
              }
            },
            "description": "Returns **200** (OK) as **application/json**"
          }
        },
        "security": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/storeTrackingValidator"
              },
              "example": {
                "coordinates": {
                  "latitude": -90,
                  "longitude": -180
                },
                "run": 1
              }
            }
          }
        }
      }
    },
    "/": {
      "get": {
        "summary": "route",
        "description": "\n\n __ - ****",
        "parameters": [],
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {}
            }
          }
        },
        "security": []
      }
    }
  },
  "tags": [
    {
      "name": "ROUTES",
      "description": "Everything related to ROUTES"
    },
    {
      "name": "ROUTES",
      "description": "Everything related to ROUTES"
    },
    {
      "name": "STOPS",
      "description": "Everything related to STOPS"
    },
    {
      "name": "STOPS",
      "description": "Everything related to STOPS"
    },
    {
      "name": "TRACKS",
      "description": "Everything related to TRACKS"
    }
  ]
}
